server:
  port: 8080
spring:
  jackson:
    date-format: yyyy-MM-dd'T'HH:mm:ss.SSS
    serialization:
      write-dates-as-timestamps: false
  datasource:
    url: jdbc:postgresql://localhost:5432/note_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        hbm2ddl:
          auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
